In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn import tree

from sklearn import datasets
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, cross_validate
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeClassifier



# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
# Set Seaborn aesthetic parameters to defaults
sns.set()
print('Setup Complete')

Setup Complete


In [2]:
#load the dataset and return it
def load_data():
    iris_data = datasets.load_iris()
    return iris_data

In [3]:
dataset = load_data()
load_data().feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:

def dataset_to_pandas():
    ''' 
    put the dataset into a pandas DF using the feature names as columnsç
    rename the column name so the dont include the '(cm)'
    add 2 columns one with the target and another with the target_names
    ''' 
    
    df = pd.DataFrame(dataset['data'], columns=dataset['feature_names'])
    df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width']
    df['target'] = dataset['target']
    df['class'] = dataset.target_names[dataset.target]

    #df['class'] = pd.Categorical.from_codes(dataset.target, dataset.target_names) #Make a Categorical type from codes and categories or dtype.
    #here the codes are the target values and the dtype will be target_names
    return df

In [5]:
df_iris = dataset_to_pandas()
df_iris

sepal length  sepal width  petal length  petal width  target      class
0             5.1          3.5           1.4          0.2       0     setosa
1             4.9          3.0           1.4          0.2       0     setosa
2             4.7          3.2           1.3          0.2       0     setosa
3             4.6          3.1           1.5          0.2       0     setosa
4             5.0          3.6           1.4          0.2       0     setosa
..            ...          ...           ...          ...     ...        ...
145           6.7          3.0           5.2          2.3       2  virginica
146           6.3          2.5           5.0          1.9       2  virginica
147           6.5          3.0           5.2          2.0       2  virginica
148           6.2          3.4           5.4          2.3       2  virginica
149           5.9          3.0           5.1          1.8       2  virginica

[150 rows x 6 columns]

In [6]:
def ohe():
    dummy = pd.get_dummies(df_iris, columns=["target"])
    return dummy
ohe()

sepal length  sepal width  petal length  petal width      class  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     target_0  target_1  target_2  
0           1         0         0  
1           1         0         0  
2           1         0         0  
3           1         0         0  
4           1         0         0  
..        ...       ...       ...  
145         0         0         1  
146         0         0         1  
147         0         0         1  
148         0         0         1  
149         0         0         1  

[150 rows x 8 columns]

In [7]:
Y = df_iris.target.to_numpy()
X = df_iris[['sepal length','sepal width']].to_numpy() 


In [8]:
X = df_iris[['sepal length', 'sepal width']].values
print(X.shape)
X[:5]

(150, 2)


array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [9]:
#Split the data into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.8, random_state = 42)

In [10]:
#normalize the dataset
#create and fit the scaler object on the training data

scaling = StandardScaler() 
X_train =  scaling.fit_transform(X_train)
X_test = scaling.fit_transform(X_test)

X_train[:5]

array([[-1.47393679,  1.20365799],
       [-0.13307079,  2.99237573],
       [ 1.08589829,  0.08570939],
       [-1.23014297,  0.75647855],
       [-1.7177306 ,  0.30929911]])

In [11]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,Y_train)

#Predict the response for test dataset
Y_pred = clf.predict(X_test)

In [12]:
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))

Accuracy: 0.8333333333333334


Second Exercise

In [22]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

zoo_df = pd.read_csv('zoo.data', header=None)
X = zoo_df.iloc[:, 1:16]
y = zoo_df[17]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
model = DecisionTreeClassifier(random_state=6)
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions)
print(y_test.values)
accuracy = accuracy_score(y_test, predictions)
#suggest 
#Dec_tree_accu = accuracy_score(y_test, predictions)
print(accuracy)

[3 4 4 1 1 1 2 4 1 1 7 1 2 7 4 6 1 6 2 4 2 3 1 2 1 1]
[5 4 4 1 1 1 2 4 1 1 7 1 2 7 4 6 1 6 2 4 2 3 1 2 1 1]
0.9615384615384616


In [29]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

zoo_df = pd.read_csv('zoo.data', header=None)
X = zoo_df.iloc[:, 1:16]
y = zoo_df[17]
'''
class sklearn.tree.DecisionTreeClassifier(criterion='gini', 
splitter='best', max_depth=None, min_samples_split=2, 
min_samples_leaf=1, max_features=None, random_state=None, 
min_density=None, compute_importances=None, max_leaf_nodes=None)
'''
kfold = KFold(n_splits=15)
X_train_z, X_test_z, y_train_z, y_test_z = train_test_split(X, y, random_state=0)
model = DecisionTreeClassifier(criterion='gini', random_state=8)
model.fit(X_train_z, y_train_z)
predictions = model.predict(X_test_z)
result = cross_val_score(model, X_test_z, y_test_z, cv=kfold)
print(result)
print('The mean accuracy is %f' %(result.mean()))
print(predictions)
print(y_test_z.values)


[0.5 1.  1.  1.  1.  1.  1.  1.  1.  1.  0.5 1.  1.  1.  1. ]
The mean accuracy is 0.933333
[5 4 4 1 1 1 2 4 1 1 7 1 2 7 4 6 1 6 2 4 2 3 1 2 1 1]
[5 4 4 1 1 1 2 4 1 1 7 1 2 7 4 6 1 6 2 4 2 3 1 2 1 1]


In [32]:
accuracy = accuracy_score(y_test, predictions)
print(accuracy)

1.0


# Part II

Random Forest 

In [35]:
#Random Forest 
#iris_data
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score



In [57]:
#default_Modeling
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

forest_default = RandomForestRegressor(random_state=1)
forest_default.fit(X_train, y_train)
predic_default_forest = forest_default.predict(X_test)
kfold = KFold(n_splits=10)

# Accuracy 
def accuracy_check(t,p):
    a =[]
    for i in range(len(t)):
        a.append((p[i]/t[i])*100)
    a = np.array(a)
    return np.mean(a)

#forest_accuracy1 = accuracy_score(y_test, predic_default_forest )
forest_accuracy = cross_val_score(y_test, predic_default_forest , cv=kfold)
print(forest_accuracy)


TypeError: estimator should be an estimator implementing 'fit' method, 26    5
86    4
2     4
55    1
75    1
94    1
16    2
73    4
54    1
96    1
53    7
93    1
78    2
13    7
7     4
30    6
22    1
24    6
33    2
8     4
43    2
62    3
3     1
71    2
45    1
48    1
Name: 17, dtype: int64 was passed

In [56]:
#try some changes 
kfold = KFold(n_splits=10)
forest_model = RandomForestRegressor(n_estimators = 1000 , random_state=1)
forest_model.fit(X_train, y_train)
predic_forest = forest_model.predict(X_test)

# Accuracy 
result_R = cross_val_score(forest_model, X_test, y_test, cv=kfold)
print('The mean accuracy is %f' %(result_R.mean()))
# accuracy = accuracy_score(y_test, predic_forest )
# print( 'Random Forest Accuracy ', accuracy*100,'%')
# print(predic_default_forest)

The mean accuracy is -1.478878


In [ ]:
#zoo dt
kfold = kfold(n_splits = )

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6c28b595-5f74-4b59-965a-54b1f3dd0300' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>