In [2]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [8]:
arrayToSwap = np.random.randint(0,16,(4,4))
print("Original array:\n",arrayToSwap)
arrayToSwap[[0,1]]=arrayToSwap[[1,0]]
print("Swaped array:\n",arrayToSwap)

Original array:
 [[ 4  2  2 12]
 [ 0 13 14 13]
 [ 4  5  1  4]
 [15  0 12  4]]
Swaped array:
 [[ 0 13 14 13]
 [ 4  2  2 12]
 [ 4  5  1  4]
 [15  0 12  4]]


**75. How to compute averages using a sliding window over an array?**

In [15]:
"""
This function will be taking the convolution of the sequence x and a 
sequence of ones of length w. Note that the chosen mode is valid so that 
the convolution product is only given for points where the sequences overlap completely.
"""
def sliding_window(x, window_size):
    return np.convolve(x, np.ones(window_size), 'valid') / window_size

#Creating a test Array
testArray = np.array([7,2,3,9,1,5,6,8,0,4])

#Testing for a window of length 2
result = sliding_window(testArray, 2)
print("Sliding window averages is :",result)

Sliding window averages is : [4.5 2.5 6.  5.  3.  5.5 7.  4.  2. ]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=bd98ef8c-5d48-4869-a08c-0388d68e7ac9' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>