In [2]:
# Import the needed libraries
import math
import random
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [12]:
randValues = np.random.randint(1,100,(10,10))
print("Array is\n", randValues)
minElement = np.amin(randValues)
print('Minimum element from Numpy Array : ', minElement)
maxElement = np.amax(randValues)
print('Maximum element from Numpy Array : ', maxElement)


Array is
 [[39 14 69 64 82 23 14 72 82 20]
 [63 37 15 36  8 80 29 27 35 96]
 [21 76 15 33 86 65 21 78 31 86]
 [11 59 22 80 64 64 37 40 63  8]
 [42 74 26 62  8 94 40 49 33 81]
 [92 96 67 12 68 90 53 77 94 11]
 [59 33  4 62 99 16 49 62 18  6]
 [45 62 63 43 88 37  4 51 30 73]
 [50 50 26  5 23 50 23 46 73 62]
 [27 93 27 28 57 59  6 58 62 24]]
Minimum element from Numpy Array :  4
Maximum element from Numpy Array :  99


**15. Create a 2d array with 1 on the border and 0 inside**

In [17]:
twodArray = np.ones((10,10))
twodArray[1:-1,1:-1] = 0
twodArray

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3482001f-b53a-4d76-8020-0c4298003c30' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>